[build]
builder = "NIXPACKS"
buildCommand = "cd zapspy/backend && npm install"

[deploy]
startCommand = "cd zapspy/backend && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
